[browser]

# Internet address where users should point their browsers in order to
# connect to the app. Can be IP address or DNS name and path.
# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser
# Default: "localhost"
serverAddress = "localhost"

[theme]
# Primary accent for interactive elements
primaryColor = "#F17C3B"
# Background color for the main content area
backgroundColor = "#FFFFFF"
# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#8d8a83"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
