version: "3.9"

services:
  flask-app:
    build: /app
    ports:
      - "5001:5001"  # Expose Flask app port
    volumes:
      - .:/app  # Mount current directory to application code
    depends_on:
      - database

  database:
    image: postgres:14.0  # Use a PostgreSQL image
    environment:
      - POSTGRES_USER=user  # Database username
      - POSTGRES_PASSWORD=password  # Database password
      - POSTGRES_DB=sentiment_db  # Database name
    volumes:
      - sentiment_db:/var/lib/postgresql/data  # Persistent data volume for database

volumes:
  sentiment_db:  # Define a named volume for database persistence
